<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFVX0BV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFVX0BV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIFVX0BV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIFVX0BV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIFVX0BV\App_KernelDevDebugContainer([
    'container.build_hash' => 'IFVX0BV',
    'container.build_id' => 'e9830001',
    'container.build_time' => 1591549482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFVX0BV');
